export interface Patient {
    entity_id: number,
    ptn_active_flag: string,
    ptn_address: string,
    ptn_city: string,                                 
    ptn_comments: string,
    ptn_date_of_birth: string,
    ptn_first_nm: string,
    ptn_home_phone: string,
    ptn_id: number,
    ptn_last_nm: string,
    ptn_mid_init: string,
    ptn_mobile_phone: string,
    ptn_occupation: string,
    ptn_sex: string,
    ptn_ssn: string,
    ptn_ssn_last4?: string,
    ptn_state: string,
    ptn_zip: string,
    lw_id?: number | null,
    provider_id?: number | null,
    ic_id?: number | null,
    ptn_date_of_accident?: string | null,
    ptn_policy_no?: string | null,
    ptn_claim_no?: string | null,
    ptn_policyholder?: string | null
  }